coverage:
  precision: 2
  round: down
  range: "90...100"

  status:
    project: 
      default:
        target: auto
        threshold: 5%
        base: auto 
    patch: no
    changes: no

comment: on