# Generated by Django 3.2.12 on 2022-03-21 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BookClub', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookshelf',
            options={'ordering': ['-id']},
        ),
    ]
