# Generated by Django 3.2.12 on 2022-02-11 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookClub', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('ISBN', models.CharField(max_length=15, unique=True)),
                ('author', models.CharField(max_length=100)),
                ('publicationYear', models.DateField()),
                ('publisher', models.CharField(max_length=100)),
                ('imageS', models.URLField(blank=True)),
                ('imageM', models.URLField(blank=True)),
                ('imageL', models.URLField(blank=True)),
            ],
        ),
    ]
