# Generated by Django 3.2.12 on 2022-03-19 16:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BookClub', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserToUserRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship_type', models.IntegerField(choices=[(0, 'Following'), (1, 'Followee'), (2, 'Mutual')])),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('source_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_user_relationships', to=settings.AUTH_USER_MODEL)),
                ('target_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_user_relationships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('source_user', 'target_user')},
            },
        ),
    ]
