# Generated by Django 3.2.12 on 2022-03-20 13:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BookClub', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertouserrelationship',
            name='source_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_relationships_source', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usertouserrelationship',
            name='target_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_relationships_target', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='usertouserrelationship',
            constraint=models.UniqueConstraint(fields=('source_user', 'target_user'), name='unique_booking'),
        ),
    ]
