# Generated by Django 3.2.12 on 2022-03-17 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookClub', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='saved_booklists',
            field=models.ManyToManyField(to='BookClub.BookList'),
        ),
    ]
