# Generated by Django 3.2.12 on 2022-03-24 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookClub', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='featuredbooks',
            name='reason',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
