# Generated by Django 3.2.12 on 2022-03-12 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BookClub', '0002_alter_booklist_books'),
        ('BookClub', '0002_event'),
    ]

    operations = [
    ]
