# Generated by Django 3.2.12 on 2022-03-14 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookClub', '0002_auto_20220314_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booklist',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
