# Generated by Django 3.2.11 on 2022-02-11 18:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookClub', '0002_club_url_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='url_name',
            field=models.CharField(max_length=100, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_url_name', message='Can contain A-Z, a-z and 0-9 and underscores characters only.', regex='^[a-zA-Z0-9_]+$')]),
        ),
    ]
