# Generated by Django 3.2.12 on 2022-03-24 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookClub', '0002_user_saved_booklists'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='saved_booklists',
            field=models.ManyToManyField(blank=True, to='BookClub.BookList'),
        ),
    ]
