# Generated by Django 3.2.11 on 2022-02-15 20:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BookClub', '0003_booklist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_time', models.DateTimeField()),
                ('created_on', models.DateField(auto_now_add=True)),
                ('location', models.CharField(blank=True, max_length=120)),
                ('title', models.CharField(max_length=120)),
                ('description', models.CharField(max_length=250)),
                ('type', models.CharField(choices=[('B', 'Book'), ('C', 'Club'), ('S', 'Social'), ('O', 'Other')], max_length=1)),
                ('book', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='BookClub.book')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BookClub.club')),
                ('members', models.ManyToManyField(related_name='meeting_attendees', to=settings.AUTH_USER_MODEL)),
                ('organiser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_organiser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
