# Generated by Django 3.2.12 on 2022-02-27 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookClub', '0003_booklist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booklist',
            name='books',
            field=models.ManyToManyField(to='BookClub.Book'),
        ),
    ]
