# Generated by Django 3.2.11 on 2022-02-13 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BookClub', '0002_alter_user_username'),
        ('BookClub', '0003_alter_club_url_name'),
    ]

    operations = [
    ]
