# Generated by Django 3.2.12 on 2022-02-16 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BookClub', '0004_merge_20220213_2307'),
    ]

    operations = [
        migrations.RenameField(
            model_name='club',
            old_name='url_name',
            new_name='club_url_name',
        ),
    ]
