# Generated by Django 3.2.11 on 2022-02-19 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookClub', '0005_rename_url_name_club_club_url_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booklist',
            name='books',
            field=models.ManyToManyField(to='BookClub.Book'),
        ),
    ]
