# Generated by Django 3.2.11 on 2022-02-16 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BookClub', '0004_meeting'),
        ('BookClub', '0005_rename_url_name_club_club_url_name'),
    ]

    operations = [
    ]
