# Generated by Django 3.2.11 on 2022-02-22 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BookClub', '0006_auto_20220222_1812'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['-id']},
        ),
    ]
