# Generated by Django 3.2.12 on 2022-02-24 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookClub', '0007_bookreview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booklist',
            name='created_on',
            field=models.DateField(auto_now_add=True),
        ),
    ]
