# Generated by Django 3.2.11 on 2022-02-24 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BookClub', '0007_alter_book_options'),
        ('BookClub', '0007_bookreview'),
    ]

    operations = [
    ]
