# Generated by Django 3.2.12 on 2022-02-23 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BookClub', '0006_alter_booklist_books'),
        ('BookClub', '0007_bookreview'),
    ]

    operations = [
    ]
