# Generated by Django 3.2.11 on 2022-02-25 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BookClub', '0008_alter_booklist_created_on'),
        ('BookClub', '0008_merge_0006_alter_booklist_books_0007_bookreview'),
    ]

    operations = [
    ]
