from .static import *
from .action_views import *

from BookClub.views.users.authentication import *
from BookClub.views.clubs.clubs import *
from BookClub.views.users.authentication import *
from BookClub.views.clubs.lists import *
from BookClub.views.users.user import *
from BookClub.views.clubs.membership import *
from BookClub.views.meetings.edit_meeting import *
from BookClub.views.library.library import *
from BookClub.views.library.book import *
from BookClub.views.library.booklists import *
from BookClub.views.meetings.meetings import *
from BookClub.views.library.reviews import *
from BookClub.views.forum.forum import *
from BookClub.views.async_views.vote import *
from BookClub.views.async_views.book_search import *
from BookClub.views.clubs.polls import *
from BookClub.views.meetings.agenda import *
from BookClub.views.bookshelf.bookshelf import *
from BookClub.views.bookshelf.add_to_bookshelf import *
from BookClub.views.bookshelf.update_in_bookshelf import *
from BookClub.views.bookshelf.remove_from_bookshelf import *
